### PR TITLE
Fix for youtube url fetch metadata issue

### PR DESCRIPTION
**Pull request by nafis042**
This pull request fixes youtube url fetch metadata issue. adding just a user-Agent field in the request header fixes the issue. i don't think it will break anything. if anything breaks please comment here

### CODE REVIEW

**Comment by LeonardoCardoso** [comment]
@nafis042 Thanks. I will test it ASAP.

**Review by abdulKarim002 — COMMENTED** [review]
@nafis042 , thanks for the PR really helped me a lot, it's working for YouTube but not working with Instagram video 

link - https://www.instagram.com/p/CKg_9H2gpQm/?utm_source=ig_web_copy_link

**Comment by nafis042** [comment]
Instagram uses open graph tags and for this, I think new regex expressions must be included. I made a quick fix for the Instagram image tag but this should be handled properly for video, title, description as well.

**Comment by abdulKarim002** [comment]
@nafis042  tested link on Insta, working great
​​​​​​​

**Comment by LeonardoCardoso** [comment]
@nafis042 @abdulKarim002 Cool! Thanks! I will have a look at it this weekend and push a new version. Thanks for the contribution.

**Pull request merged**
